"""
Initial database with tables: User, Links

Revision ID: 79373ca62ee3
Revises: 
Create Date: 2022-10-21 19:02:45.978574
"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79373ca62ee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', fastapi_users_db_sqlalchemy.guid.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('Links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('original_link', sa.Text(), nullable=False),
    sa.Column('short_link', sa.String(length=16), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.guid.GUID(), nullable=True),
    sa.Column('number_of_uses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('short_link')
    )
    op.create_index(op.f('ix_Links_original_link'), 'Links', ['original_link'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Links_original_link'), table_name='Links')
    op.drop_table('Links')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
